services:
  db:
    image: postgis/postgis:16-3.4
    container_name: moodgallery_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: moodgallery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: moodgallery_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
